### ISSUE TITLE
[BUG] Y-level of lava incorrectly displayed on scoreboard during game.

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#3]
### [BUG] Y-level of lava incorrectly displayed on scoreboard during game. 

**Description:** When starting a game, the Y-level of the current lava is incorrectly displayed on the scoreboard. It is displayed 1 coordinate too low, for example, when the lava is at Y-level 10, the scoreboard shows that the lava is at level 9. It would be nice if this could be fixed so that the scoreboard becomes even more accurate.

**Comment by DuckMC** [comment]
The version of my server is `1.21.1` and I am using ` LavaRise-2.0.1`

This is my current arenas.yml file.

```yml
version: 1
test:
  lobby:
    world: test
    x: 8
    y: 4
    z: 8
    yaw: -148.52896
    pitch: 3.4426763
  gameArea:
    world: test
    Bottom:
      x: -8
      y: 4
      z: -8
    Top:
      x: 24
      y: 29
      z: 24
  lavaLevel: 25
  minimumPlayers: 2
  maximumPlayers: 10
  pvp: true
```

I recorded a a video showing the bug. Hopefully the problem will become clear this way.
Video link: https://www.youtube.com/watch?v=0k-wjqOzAs8
